name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2

     - name: setup gcloud
       run: |
        curl https://sdk.cloud.google.com | bash > /dev/null
        source $HOME/google-cloud-sdk/path.bash.inc

     - name: setup kubectl
       run: gcloud components install kubectl

