name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2

     - name: setup gcloud
       run: |
        curl https://sdk.cloud.google.com | bash > /dev/null
        source $HOME/google-cloud-sdk/path.bash.inc

     - name: setup kubectl
       run: |
          curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-247.0.0-linux-x86_64.tar.gz
          tar zxvf google-cloud-sdk-247.0.0-linux-x86_64.tar.gz google-cloud-sdk
          mv /usr/lib/google-cloud-sdk /usr/lib/google-cloud-sdk-ORIG
          mv google-cloud-sdk /usr/lib/
          gcloud components update

